rodeo/rodeo.py
preference saves weren't working in python 3.4
=> BUG: fix .rodeorc handling for python3

rodeo/rodeo.py
see https://github.com/pypa/pip/issues/2695
=> to have a refreshable package list

rodeo/rodeo.py
=> python3 compatibility effort

rodeo/rodeo.py, rodeo/utils.py
Hi
I've fixed small bugs:
1) Calling `slugify.slugify` instead of just `slugify`
2) Default encoding for source file - was not starting because utils.py file has Unicode characters but default encoding was not set for source file. I've added 'coding' comment at the beginning, also added it to `rodeo.py` file
=> Minor fixes

src/browser/jsx/components/ace-pane/ace-pane.jsx, src/browser/jsx/services/python-completer.js, src/node/index.js, src/node/kernels/python/client.js, src/node/kernels/python/client.test.js
New Features
- use Tab or Control-Space to trigger auto-completion.
=> autocomplete works

src/browser/jsx/components/preferences/preferences-input.jsx, src/browser/jsx/components/preferences/preferences-item.jsx, src/browser/jsx/components/preferences/preferences-list.css, src/browser/jsx/components/preferences/preferences-list.jsx, src/browser/jsx/components/preferences/save-changes-button-group.jsx, src/browser/jsx/containers/file-viewer/file-viewer.actions.js, src/browser/jsx/containers/file-viewer/file-viewer.jsx, src/browser/jsx/containers/file-viewer/file-viewer.reducer.js, src/browser/jsx/containers/preferences-viewer/preferences-viewer.jsx, src/browser/jsx/services/preferences-mapper.js, src/node/index.js
Fixes:
- On initial load (without localStorage because they've never loaded the app before), use their home directory for the file viewer.
=> File viewer initial load

src/browser/jsx/containers/terminal/terminal.reducer.js
Fixes:
- packages were being assigned to a strange place, fixed now.
=> fix packages

src/node/services/updater.js
New Features:
- it understands that it is the current version or not
=> understands that it is the current version

src/browser/jsx/components/setup/python-test-input.jsx, src/browser/jsx/containers/setup-viewer/setup-viewer.actions.js, src/browser/jsx/containers/setup-viewer/setup-viewer.reducer.js, src/node/kernels/python/client.js
=> understand ~ and %HOME%

src/browser/jsx/components/sidebar/sidebar.jsx
=> updated ops sidebar route

src/browser/jsx/components/sidebar/sidebar.actions.js, src/browser/jsx/components/sidebar/sidebar.jsx
Changes:
Sidebar
- Added icon, copy, link for docs
- Added icon, copy, link for discourse
- Added icon, copy, link for github repo
=> added external links for docs, discussion and github

package.json, src/browser/jsx/actions/iopub.js, src/browser/jsx/actions/kernel.js, src/browser/jsx/components/ace-pane/ace-pane.jsx, src/browser/jsx/components/plot-viewer/plot-viewer.actions.js, src/browser/jsx/containers/preferences-viewer/preferences-viewer.jsx, src/browser/jsx/containers/preferences-viewer/preferences.actions.js, src/browser/jsx/containers/preferences-viewer/preferences.yml, src/browser/jsx/containers/setup-viewer/setup-viewer.actions.js, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/services/ace-decorators.js, src/browser/jsx/services/ace-settings.js, src/browser/jsx/services/ace-shortcuts.js, src/browser/jsx/services/client-discovery.js, src/browser/jsx/services/client.js, src/browser/jsx/services/preferences-mapper.js, src/browser/jsx/services/python-completer.js, src/browser/jsx/services/system-facts.js, src/node/index.js, src/node/kernels/python/client.js, src/node/kernels/python/steve-irwin.js, src/node/services/browser-windows.js, src/node/services/updater.js
Fixes:
- only a single instance of python should be allowed to run at a time
- kill the other instance before changing to a new one
=> Single python

src/browser/jsx/components/preferences/preferences-input.jsx, src/browser/jsx/components/preferences/preferences-item.jsx, src/browser/jsx/containers/preferences-viewer/preferences-viewer.jsx, src/browser/jsx/containers/preferences-viewer/preferences.yml, src/browser/jsx/entry/main.js, src/browser/jsx/services/cid.js, src/browser/jsx/services/guid.js, src/browser/jsx/services/preferences-mapper.js, src/browser/jsx/services/store.js, src/browser/jsx/services/system-facts.js, src/browser/jsx/services/track.js, src/node/index.js
New Feature
- When the app first loads, ping a server with the version.
We're going to use this to gauge adoptable of versions of Rodeo and how well the auto-update is working.  Otherwise, we wouldn't have any idea.  There is a (hopefully!) friendly message in the console that we're doing this, and an explanation of how to disable it from the Preferences menu.
=> application-metrics

src/browser/jsx/actions/kernel.js, src/browser/jsx/components/ace-pane/ace-pane.jsx, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/services/ace-shortcuts.js, src/node/index.js
Fixes https://github.com/yhat/rodeo/issues/316
Shift-cmd-enter to run the whole file as well.
=> Run button

src/browser/jsx/components/preferences/preferences-item.jsx, src/browser/jsx/components/preferences/preferences-list.css, src/browser/jsx/components/preferences/preferences-select.jsx, src/browser/jsx/containers/preferences-viewer/preferences.yml, src/browser/jsx/services/ace-settings.js
New Feature:
- vim and emacs keybinding support
=> Preferences select

src/browser/jsx/containers/editor-tab-group/editor-tab-group.jsx, src/browser/jsx/containers/studio-layout/studio-layout.css
Same as previous, only w/ code in the write place...;)
=> added text to run button

scripts/osx/sign.sh, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/containers/terminal/terminal.actions.js, src/browser/jsx/containers/terminal/terminal.css, src/browser/jsx/containers/terminal/terminal.jsx, src/browser/jsx/services/ace-python-completer.js, src/browser/jsx/services/ace-settings.js, src/browser/jsx/services/text-util.js
New Features:
- Add auto-complete to the console on tab keypress.
=> Auto complete console

src/node/index.js, src/node/kernels/python/client.js, src/node/kernels/python/language.js, src/node/kernels/python/steve-irwin.js
Fixes https://github.com/yhat/rodeo/issues/342
=> PATH includes for darwin

src/node/kernels/python/start_kernel.py
New Features:
- slowly back off the CPU when there is nothing happening in python.
This is until I dig until Jupyter's code more and figure out a way to subscribe for updates instead, probably using zeromq.
Fixes https://github.com/yhat/rodeo/issues/345
=> cpu-backoff

.travis.yml, src/node/index.js
Enables building on master branch.
=> enable-building

src/browser/jsx/services/registration.js
Changed Register to a POST request.  Latency improved a ton.
=> updated register to post request, a whole lot faster

src/browser/jsx/components/plot-preview/html-flat.svg, src/browser/jsx/components/plot-preview/plot-preview.css, src/browser/jsx/containers/plot-viewer/plot-viewer.actions.js, src/browser/jsx/containers/plot-viewer/plot-viewer.reducer.js, src/node/menus/application.yml
New Feature:
- &#8984; + 4 to focus the latest plot.
Patch:
- newest plots are at the top.
=> focus plot with command

src/browser/jsx/actions/application.js, src/browser/jsx/actions/kernel.js, src/browser/jsx/components/sidebar/sidebar.actions.js, src/browser/jsx/containers/setup-viewer/setup-viewer.actions.js, src/browser/jsx/services/ipc-dispatcher.js
=> added tracking metrics

src/browser/jsx/containers/variable-viewer/variable-viewer.jsx
New Features
- column resizing in the environment viewer
=> add column resizing

src/node/index.js, src/node/kernels/python/client.js, src/node/kernels/python/steve-irwin.js, src/node/services/processes.js
Prevent stderr or process errors from rejecting Python instances.
=> remove process failure from process error or stderr, only by exceptions

src/browser/jsx/components/ace-pane/ace-pane.jsx, src/browser/jsx/containers/editor-tab-group/editor-tab-group.jsx, src/browser/jsx/containers/editor-tab-group/editor-tab-group.reducer.js, src/browser/jsx/containers/editor-tab-group/initial-story.py, src/browser/jsx/containers/setup-viewer/setup-viewer.jsx
Start the app with starting text so we don't scare people with a blank canvas.
=> starting-text

package.json, src/browser/jsx/components/data-frame/data-frame.jsx, src/browser/jsx/containers/setup-viewer/install-instructions.md, src/browser/jsx/containers/startup.css, src/browser/jsx/containers/startup.jsx, src/browser/jsx/containers/startup.less, src/browser/jsx/containers/variable-viewer/variable-viewer.jsx, src/node/index.js
Fixes:
- spelling of matplotlib
- link to Anaconda is now clickable on Windows and Linux
- always refresh data-frame dragging
=> Drag and quit

src/browser/jsx/actions/application.js, src/browser/jsx/actions/kernel.js, src/browser/jsx/components/data-frame/data-frame-loading-icon.jsx, src/browser/jsx/components/data-frame/data-frame.css, src/browser/jsx/components/data-frame/data-frame.jsx, src/browser/jsx/components/sidebar/sidebar.actions.js, src/browser/jsx/containers/setup-viewer/setup-viewer.actions.js, src/browser/jsx/containers/variable-table-viewer.jsx, src/browser/jsx/entry/main.js, src/browser/jsx/services/client-discovery.js, src/browser/jsx/services/ipc-dispatcher.js, src/browser/jsx/services/track.js
Fixes:
- DataFrame viewing that has apostrophes now works.
- Cool loading icon for loading large DataFrames.
=> Data frames empty

src/browser/jsx/containers/editor-tab-group/editor-tab-group.jsx, src/browser/jsx/entry/free-tabs-only.html, src/browser/jsx/entry/main.html, src/browser/jsx/entry/startup.html
New Features
- Allow unicode in the UI, and show shortcuts for Run Line and Run Script
=> show unicode

src/browser/jsx/components/data-frame/data-frame.css, src/browser/jsx/components/data-frame/data-frame.jsx, src/browser/jsx/components/plot-preview/plot-preview.css, src/browser/jsx/components/plot-preview/plot-preview.jsx, src/browser/jsx/components/preferences/preferences-list.css, src/browser/jsx/containers/terminal/terminal.actions.js, src/browser/jsx/containers/terminal/terminal.jsx, src/browser/jsx/containers/variable-viewer/variable-viewer.jsx, src/browser/jsx/services/client.js, src/browser/jsx/services/global-observer.js, src/browser/jsx/services/terminal-shortcuts.js, src/node/index.js, src/node/services/browser-windows.js
New Features
- Clean up the scrollbars on Windows.
- Improved startup of kernel (remove the delay on first command run)
- Prevent bad render of variable viewer on startup
=> Clean up scroll bars

src/browser/jsx/services/application-control.js, src/browser/jsx/services/track.js
New Feature
- start switching away from google analytics, because corporations are evil.  Better to be open source with Piwik!
=> Non ga tracking

src/browser/jsx/services/ace-shortcuts.js
Allow indent and outdent on selected text using Tab and Shift-Tab
=> indent-outdent

src/browser/jsx/services/ace-python-completer.js
New Features
- better docstrings
- it now understands `thing.thing`
=> better docstrings

src/browser/jsx/containers/editor-tab-group/initial-story.py
Replace 
```python
import pip		
pip.main([...])
```
with
```python
! pip install ...
```
in starting script
=> first task simplify

src/browser/jsx/actions/kernel.js, src/browser/jsx/components/tab-text/tab-text.css, src/browser/jsx/components/tab-text/tab-text.jsx, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/containers/terminal/terminal.reducer.js, src/browser/jsx/services/client.js, src/node/index.js, src/node/kernels/python/client-response.js, src/node/kernels/python/client-response.test.js, src/node/kernels/python/client.js, src/node/kernels/python/client.test.js, src/node/kernels/python/langs/python-patch.py
Show the working directory to the user
=> Show working directory

src/browser/jsx/components/plot-preview/plot-preview.css, src/browser/jsx/components/preferences/preferences-list.css, src/browser/jsx/components/search-text-box/search-text-box.css
Reduce the size of the minimap in the plot-viewer
=> smaller-minimap

src/node/index.js, src/node/kernels/python/client.js, src/node/services/env.js, src/node/services/win32/system.js, src/node/services/win32/system.test.js
Gets environment variables for windows dynamically whenever we launch a process.
=> Windows env

package.json, src/browser/jsx/components/sidebar/slideout-dialog.css, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/containers/terminal/terminal.actions.js, src/browser/jsx/containers/terminal/terminal.jsx, src/browser/jsx/services/client.js, src/node/index.js, src/node/kernels/python/check_python.py, src/node/kernels/python/client.js, src/node/kernels/python/client.test.js, src/node/kernels/python/language.js, src/node/kernels/python/start_kernel.py, src/node/kernels/python/steve-irwin.js, src/node/services/browser-windows.js, src/node/services/env.js, src/node/services/files.js, src/node/services/win32/system.js
Get fresh environment variables whenever a new process is started on Windows.
=> Windows env better

package.json, scripts/osx/dist-linux.sh, src/node/index.js, src/node/services/files.js, tasks/dist.js
Fix issue where `~` was not recognized as the home directory.
=> working-directory-set

src/browser/jsx/containers/studio-layout/studio-layout.css, src/browser/jsx/containers/studio-layout/studio-layout.jsx, src/browser/jsx/containers/terminal/terminal.actions.js, src/browser/jsx/containers/terminal/terminal.jsx, src/browser/jsx/services/terminal-shortcuts.js
Add clear, restart and interrupt buttons.
=> kill and restart buttons

src/browser/jsx/components/ace-pane/ace-pane.jsx, src/browser/jsx/components/plot-preview/background-plot.jsx, src/browser/jsx/components/plot-preview/plot-preview.css, src/browser/jsx/components/plot-preview/plot-preview.jsx, src/browser/jsx/containers/editor-tab-group/editor-tab-group.actions.js, src/browser/jsx/containers/editor-tab-group/editor-tab-group.reducer.js, src/browser/jsx/containers/plot-viewer/plot-viewer.actions.js, src/browser/jsx/containers/plot-viewer/plot-viewer.jsx, src/browser/jsx/containers/plot-viewer/plot-viewer.reducer.js, src/browser/jsx/containers/preferences-viewer/preferences.yml, src/browser/jsx/containers/setup-viewer/setup-viewer.actions.js, src/browser/jsx/services/ace-settings.js, src/browser/jsx/services/ace-shortcuts.js, src/browser/jsx/services/registration.js, src/node/index.js, src/node/services/files.js, src/node/services/installer/commands.js, src/node/services/installer/index.js, src/node/services/plot-server.js, src/node/services/processes.js
Fix squirrel installer
Add Use Soft Tabs Preference
Fix Tab Spaces Preference
Fix Save File recommendation
=> Fix squirrel installer

src/node/index.js, src/node/services/installer/index.js, src/node/services/log.js
There were failures and timeouts when installing Rodeo because of a bad order of running the Squirrel installer.  Fixed now.
=> install more quickly

src/node/index.js, src/node/kernels/python/client.js, src/node/services/clone.js, src/node/services/errors/process-error.js
New Features
- double timeout of executing and checking python processes
- allow individually executing ipython processes to be cancelled.
=> double timeout; cancel processes

src/browser/jsx/components/data-frame/data-frame.jsx
Fixes https://github.com/yhat/rodeo/issues/422
=> zero is now a visible column

contributing.md, src/browser/jsx/containers/editor-tab-group/editor-tab-group.actions.js, src/node/index.js, src/node/menus/application.yml
fixes https://github.com/yhat/rodeo/issues/363
=> Removing old shortcut for default variables, blank file fix, resolve HOME on save

gulpfile.js, src/browser/jsx/components/preferences/items/preferences-select.jsx, src/browser/jsx/containers/editor-tab-group/editor-tab-group.reducer.js, src/browser/jsx/containers/preferences-viewer/preferences.yml, src/browser/jsx/services/ace-settings.js
=> ace-themes

src/browser/jsx/components/setup/setup-article-preview.css, src/browser/jsx/components/setup/setup-initial.jsx, src/browser/jsx/containers/setup-viewer/articles.yml
Update the blog link to http://blog.yhat.com/posts/moving-from-r-to-python.html
=> update blog link on starting screen

src/browser/jsx/components/variable-viewer/variable-table.jsx
Fixes:
- Elise found a bug where data table were not being linked to correctly in the Environment tab.  This is now fixed.
=> fix for actionest button not updating

src/browser/jsx/components/files/file-list.jsx, src/browser/jsx/components/files/file-tree-header.css, src/browser/jsx/components/files/file-tree-header.jsx, src/browser/jsx/components/files/file-tree.jsx, src/browser/jsx/components/tree-view/tree-view-item.js, src/browser/jsx/components/tree-view/tree-view.css, src/browser/jsx/containers/file-viewer/file-viewer.actions.js, src/browser/jsx/containers/file-viewer/file-viewer.jsx
Adds "Home" and "Working Directory" as shortcuts in the file viewer
=> add go-to-home and go-to-wd buttons to file viewer

src/browser/jsx/components/variable-viewer/variable-viewer.jsx
Fixes http://discuss.yhat.com/t/environment-pane-remains-empty-after-variable-assignment/273
=> unhide variables

package.json
Add additional items to installables.
=> install-compression

package.json, src/browser/jsx/components/manage-connections/connection-config.js, src/browser/jsx/components/packages/package-search-item-detail.jsx, src/browser/jsx/components/packages/package-search-list.jsx, src/browser/jsx/containers/block-terminal-viewer/block-terminal-viewer.actions.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.actions.js, src/browser/jsx/containers/free-tab-group/free-tab-group.actions.js, src/browser/jsx/containers/free-tab-group/free-tab-group.jsx, src/browser/jsx/containers/free-tab-group/free-tab-group.reducer.js, src/browser/jsx/containers/main.reducer.js, src/browser/jsx/containers/package-search-viewer/package-search-viewer.actions.js, src/browser/jsx/containers/package-search-viewer/package-search-viewer.jsx, src/browser/jsx/containers/package-search-viewer/package-search-viewer.reducer.js
Fix the package search to work again.
=> Package search reconnect

src/browser/jsx/components/ace-pane/ace-pane.js, src/browser/jsx/components/setup/setup-article-preview.jsx, src/browser/jsx/containers/editor-tab-group/ace.actions.js, src/browser/jsx/containers/editor-tab-group/editor-commands.yml, src/browser/jsx/containers/free-tab-group/free-tab-group.actions.js, src/browser/jsx/containers/package-search-viewer/package-search-viewer.actions.js, src/browser/jsx/services/ace-shortcuts.js, src/browser/jsx/services/jupyter/python-language.js, src/node/services/browser-windows.js
Allow users to run commands with selections from the ace-pane
=> Stop input from being aggressive

src/browser/jsx/services/track.js
=> adding uid

src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.reducer.js
Fix the document-viewer-terminal reset.
=> fix-restart

src/browser/jsx/components/block-history/history-blocks/image-block.js, src/browser/jsx/components/document-terminal/document-terminal-annotation.css, src/browser/jsx/components/document-terminal/document-terminal-annotation.js, src/browser/jsx/components/document-terminal/document-terminal.js, src/browser/jsx/components/empty/empty-suggestion.js, src/browser/jsx/components/gray-info/gray-info-link.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.actions.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.reducer.js, src/browser/jsx/containers/editor-tab-group/ace.actions.js, src/browser/jsx/containers/free-tab-group/free-tab-group.jsx, src/browser/jsx/lib/ipc.js, src/browser/jsx/services/immutable-util.js, src/browser/jsx/services/jupyter/client-discovery.js, src/browser/jsx/services/store.js, src/node/index.js, src/node/services/browser-windows.js
- Change the way input is displayed to seem slightly faster
=> seems a bit faster

.eslintrc, package.json, src/browser/jsx/actions/dialogs.js, src/browser/jsx/components/about-rodeo/about-rodeo.jsx, src/browser/jsx/services/jupyter/client-discovery.js, src/browser/jsx/services/track.js, src/node/index.js, webpack.config.js
New Features
- Removes the getAppVersion and the getAppName calls to improve the speed of the application
=> Remove version call

package.json, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.js, src/browser/jsx/containers/document-terminal-viewer/features.yml, src/browser/jsx/containers/editor-tab-group/editor-commands.yml, src/browser/jsx/containers/prompt-viewer/default-commands.yml, src/browser/jsx/containers/prompt-viewer/prompt-viewer.js
Fix Ctrl-C so it clear the terminal again
Add scrolling to the Run Line command
=> Fix scroll on run line

src/browser/jsx/containers/editor-tab-group/ace.actions.js, src/browser/jsx/containers/editor-tab-group/editor-tab-group.jsx, src/browser/jsx/containers/free-tab-group/free-tab-group.jsx
Allow to run blocks automatically when clicking Run Line
=> block run on Run Line button

src/browser/jsx/components/document-terminal/document-terminal-annotation.css, src/browser/jsx/components/document-terminal/document-terminal-annotation.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.actions.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.js, src/browser/jsx/containers/document-terminal-viewer/document-terminal-viewer.reducer.js, src/browser/jsx/containers/free-tab-group/free-tab-group.jsx, src/browser/jsx/containers/preferences-viewer/preferences.yml
Focus Plots tab when they click on annotation
=> plot-tab focuses on click of annotation

src/browser/jsx/services/text-util.js, src/browser/jsx/services/text-util.test.js
Fixes https://github.com/yhat/rodeo/issues/535
=> escape xml/html

__mocks__/browser-mocks.js, package.json, src/browser/jsx/containers/prompt-viewer/prompt-viewer.js, src/browser/jsx/containers/prompt-viewer/prompt-viewer.test.js, src/browser/jsx/services/common-tabs-actions.js, src/browser/jsx/services/common-tabs-actions.test.js
Fixes https://github.com/yhat/rodeo/issues/539
=> allow international keys using alt, ctrl, meta

src/browser/components/document-terminal/document-terminal-error.js, src/browser/components/document-terminal/document-terminal-python-error.js, src/browser/containers/block-terminal-viewer/block-terminal-viewer.actions.js, src/browser/containers/document-terminal-viewer/document-terminal-viewer.actions.js, src/browser/containers/document-terminal-viewer/document-terminal-viewer.js, src/browser/containers/free-tab-group/free-tab-group.jsx, src/browser/containers/global-history-viewer/global-history-viewer.js, src/browser/containers/package-search-viewer/package-search-viewer.actions.js, src/browser/containers/preferences-viewer/layout.yml, src/browser/containers/text.yml, src/browser/services/jupyter/python-language.js
Installing packages from error messages works again.
=> working install of packages again

contributing.md, package.json, src/browser/services/ipc-dispatcher.js, src/node/kernels/python/client.js, src/shared/env.js
The startup screen should only show on the second failure
=> startup-fix

package.json, src/browser/components/document-terminal/document-terminal-text.css, src/browser/containers/free-tab-group/free-tab-group.actions.js, src/browser/containers/free-tab-group/free-tab-group.reducer.js, src/browser/services/jupyter/client.js, src/shared/env.js
Bug:  When viewing variables in a popped out window, viewing the contents of a data frame didn't work.
This fixes that bug.
=> Pop out client sharing

src/browser/components/document-terminal/document-terminal-history.js, src/browser/components/prompt/prompt.css, src/browser/components/prompt/prompt.js, src/browser/containers/document-terminal-viewer/document-terminal-viewer.css, src/browser/containers/document-terminal-viewer/document-terminal-viewer.js, src/browser/containers/document-terminal-viewer/document-terminal-viewer.reducer.js, src/browser/containers/preferences-viewer/layout.yml
Adds a thin blinking cursor to the terminal / console.
=> blinking cursor

package.json, src/browser/containers/editor-tab-group/editor-tab-group.reducer.js, src/browser/containers/editor-tab-group/initial-story.py, src/browser/containers/preferences-viewer/layout.yml, src/browser/services/env.js, src/browser/services/layout-mapper.js, src/node/kernels/python/language.js, src/node/services/env.js, webpack.config.js, webpack.dev.config.js, webpack.main.config.js
Change startup script
Add more to path on Rodeo startup
=> change startup script; add more to path on Rodeo startup

package.json, src/browser/containers/main.jsx, src/browser/containers/preferences-viewer/layout.yml, src/browser/containers/text.yml, src/node/kernels/python/client.js, src/node/kernels/python/language.js
Only set the python path when they're using the builtin python
=> only set path on builtin
